"""Agent decision-trace models for debugging and tests."""

from dataclasses import dataclass, field

from engine.actions import Action


@dataclass(frozen=True, slots=True)
class DecisionRecord:
    """Structured decision record generated by an agent."""

    step_no: int
    player_id: int
    legal_actions: tuple[Action, ...]
    selected_action: Action
    rule_references: tuple[str, ...] = ()
    experience_references: tuple[str, ...] = ()
    notes: tuple[str, ...] = ()
    metadata: dict[str, object] = field(default_factory=dict)
