"""Agent decision-trace models for debugging and tests."""

from dataclasses import dataclass, field

PublicAction = dict[str, object]


@dataclass(frozen=True, slots=True)
class DecisionRecord:
    """Structured decision record generated by an agent."""

    step_no: int
    player_id: int
    observation: dict[str, object]
    legal_actions: tuple[PublicAction, ...]
    selected_action_id: int
    selected_action: PublicAction | None = None
    rule_references: tuple[str, ...] = ()
    experience_references: tuple[str, ...] = ()
    notes: tuple[str, ...] = ()
    metadata: dict[str, object] = field(default_factory=dict)
